routes/web.php
<?php

use App\Http\Controllers\LogController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//todo authentication needs to be added
Route::get('logs',[LogController::class,'index']);
Route::get('logs/{log}',[LogController::class,'show']);



Route::get('/', function () {
    return redirect()->route('login');
});

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
/**
 * @OA\Info(
 *    title="APIs For Thrift Store",
 *    version="1.0.0",
 * ),
 *    PathItem()
 *
 */
class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LogController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Modules\User\Entities\User;
use Morilog\Jalali\Jalalian;
use Spatie\Activitylog\Models\Activity;
use Spatie\Permission\Models\Role;

class LogController extends Controller
{
    protected $roleNames = [
        'SuperAdmin' => 'سوپر ادمین',
        'Univercity' => 'نماینده دانشگاه',
        'Customer' => 'کاربر سایت',
    ];

    protected function getModel($activity)
    {
        if ($activity->subject_type == null) {
            return null;
        }
        $modelNameSpace = $activity->subject_type;
        $modelClass = app($modelNameSpace);
        $model = $modelClass->withTrashed()->find($activity->subject_id);
        return $model ?? null;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->input('key') != 'rL05Q1vuw26I3988gZNyz2Q5v7JBNlcAPa8Ln0Tgu7SAIY2fEq') {
            abort(403);
        }

        $events = Activity::distinct('event')->pluck('event');
        $logNames = Activity::distinct('log_name')->pluck('log_name');
        $causerIDs = Activity::distinct('causer_id')->pluck('causer_id');

        $eventInput = $request->input('event') ?? 'all';
        $logNameInput = $request->input('log_name') ?? 'all';
        $causerIdInput = $request->input('causer_id') ?? 'all';
        $roleInput = $request->input('role') ?? 'all';


        $allRoles = Role::all();
        $foundRole = $allRoles->first(function ($singleRole) use ($roleInput) {
            return $singleRole->id == $roleInput;
        });

//        dd($foundRole);
//        dd($allRoles);
        $roles = [];
        foreach ($allRoles as $role) {
            $role->pName = $this->roleNames[$role->name];
        }
        $roles = $allRoles;
//                dd($allRoles);

        $causers = User::whereIn('id', $causerIDs)
            ->select('id', 'first_name', 'last_name')
            ->get();


        $activitiesQuery = Activity::query();

        $activitiesQuery = $request->input('event') != 'all' && $request->has('event') ? $activitiesQuery->where('event', '=', $request->input('event')) : $activitiesQuery;
        $activitiesQuery = $request->input('log_name') != 'all' && $request->has('log_name') ? $activitiesQuery->where('log_name', '=', $request->input('log_name')) : $activitiesQuery;
        $activitiesQuery = $request->input('causer_id') != 'all' && $request->has('causer_id') ? $activitiesQuery->where('causer_id', '=', $request->input('causer_id')) : $activitiesQuery;


        if ($roleInput != 'all') {
            $activitiesQuery->whereExists(function ($query) use ($foundRole) {
                $query->select(\DB::raw(1))
                    ->from('model_has_roles')
                    ->whereColumn('model_has_roles.model_id', 'activity_log.causer_id')
                    ->where('model_has_roles.model_type', '=', 'Modules\User\Entities\User') // Use your User model's actual class name
                    ->whereExists(function ($subQuery) use ($foundRole) {
                        $subQuery->select(\DB::raw(1))
                            ->from('roles')
                            ->whereColumn('roles.id', 'model_has_roles.role_id')
                            ->where('roles.name', '=', $foundRole->name);
                    });
            });
        }


        $activitiesQuery->orderBy('id', 'desc');
        $activities = $activitiesQuery->paginate(10);

        foreach ($activities as $activity) {
            $activity->roleName = $activity->causer ? $this->roleNames[$activity->causer->roles->first()->name] : null;
            $carbonActivity = Carbon::parse($activity->created_at);

            $carbonActivity->addHours(3)->addMinutes(30);

            $activity->created_at = Jalalian::fromCarbon($carbonActivity)->format('Y-m-d H:i:s');

            if (!$activity->subject) {
                $activity->subject = $this->getModel($activity);
            }
        }
//        dd($roles);
//        dd(($activities));

        return view('logs.index2',

            compact(['activities',
                'logNames', 'logNameInput',
                'causers', 'causerIdInput',
                'events', 'eventInput',
                'roles', 'roleInput'
            ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public
    function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public
    function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public
    function show(Request $request, $id)
    {

        if ($request->input('key') != 'rL05Q1vuw26I3988gZNyz2Q5v7JBNlcAPa8Ln0Tgu7SAIY2fEq') {
            abort(403);
        }

        $activity = Activity::find($id);

//        dd($activity->properties);
        $activity->created_at = Jalalian::fromDateTime($activity->created_at)->format('Y-m-d H:i:s');
        if (!$activity->subject) {
            $activity->subject = $this->getModel($activity);
        }
        return view('logs.show', compact('activity'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public
    function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public
    function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public
    function destroy($id)
    {
        //
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MessageController extends Controller
{
    //
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.admin');
    }
}

resources/views/dashboard.blade.php
@include('layouts.header')
<div class="container-fluid">
    <!-- Begin Page Header-->

    <!-- End Page Header -->
    <!-- Begin Row -->
    <div class="row flex-row">
        <!-- Begin Facebook -->
        <div class="col-xl-4 col-md-6 col-sm-6">
            <div class="widget widget-12 has-shadow">
                <div class="widget-body">
                    <div class="media">
                        <div class="align-self-center ml-5 mr-5">
                            <i class="ion-person-stalker text-twitter"></i>
                        </div>
                        <div class="media-body align-self-center">
                            <div class="title text-twitter">تعداد اعضا</div>
                            <div class="number">۱،۴۵۰</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Facebook -->
        <!-- Begin Twitter -->
        <div class="col-xl-4 col-md-6 col-sm-6">
            <div class="widget widget-12 has-shadow">
                <div class="widget-body">
                    <div class="media">
                        <div class="align-self-center ml-5 mr-5">
                            <i class="ion-social-buffer-outline text-twitter"></i>
                        </div>
                        <div class="media-body align-self-center">
                            <div class="title text-twitter">رزومه ها</div>
                            <div class="number">۱،۱۰۰</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Twitter -->
        <!-- Begin Linkedin -->
        <div class="col-xl-4 col-md-6 col-sm-6">
            <div class="widget widget-12 has-shadow">
                <div class="widget-body">
                    <div class="media">
                        <div class="align-self-center ml-5 mr-5">
                            <i class="ion-compose text-twitter"></i>
                        </div>
                        <div class="media-body align-self-center">
                            <div class="title text-twitter">وضعیت رزومه</div>
                            <div class="number">
                                @switch($status)
                                    @case(1)
                                        در انتظار تایید
                                    @break

                                    @case(2)
                                        نیازمند اصلاح
                                    @break

                                    @case(3)
                                        تایید شده
                                    @break

                                    @default
                                        ارسال نشده
                                @endswitch
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Linkedin -->
    </div>
    <!-- End Row -->
    <!-- Begin Row -->
    <div class="row flex-row">
        <div class="col-xl-12 col-md-6">
            <!-- Begin Widget 09 -->
            <div class="widget widget-09 has-shadow">
                <!-- Begin Widget Header --
                <div class="widget-header d-flex align-items-center">
                    <h2>خوش آمدید</h2>
                    <div class="widget-options">
                        <button type="button" class="btn btn-shadow">
                            تکمیل پروفایل
                        </button>
                    </div>
                </div>
                <!-- End Widget Header -->
                <!-- Begin Widget Body -->
                <div class="widget-body">
                    <div class="row">
                        <div class="col-xl-12 col-12 no-padding">
                            <div class="p-4 text-justify" style="color: #222">
                                <p style="font-size: 1.3rem; line-height: 3rem;">
                                    دستیابی به توسعه اقتصادی پایدار، یکی از مهم‌ترین دغدغه کشورهای مختلف بوده و یکی از مهمترین عوامل آن، توجه ویژه به موضوع کارآفرینی است. توسعه کارآفرینی دانش‌پایه، نیازمند توانمندسازی افراد در حوزه مهارت‌های نرم و تخصصی کارآفرینی می‌باشد که طرح ملی ترویج کارآفرینی، با هدف آموزش و توانمندسازی عادلانه دانشجویان و دانش‌ آموختگان دانشگاه‌های کشور برای اولین بار توسط معاونت نوآوری وزارت علوم، تحقیقات و فناوری و با همکاری پارک علم و فناوری دانشگاه صنعتی امیرکبیر و بر بستر شبکه مهارت و اشتغال راهه‌کار برگزار می‌گردد.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Widget 09 -->
        </div>
    </div>
    <!-- End Row -->
</div>
<!-- End Container -->
@include('layouts.footer')

resources/views/layouts/admin.blade.php
@php use Illuminate\Support\Facades\Auth; @endphp


    <!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"
            defer>
    </script>

    <script src="https://cdn.tailwindcss.com"></script>





    {{-- <script
        type="text/javascript"
        src={{ asset('/assets/js/admin.js') }}
        defer
         ></script> --}}
    <meta name="_token" content="{{ csrf_token() }}">
    {{--    <script src="{{ asset('js/custom.js') }}" defer></script>--}}

    {{--    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>--}}

    <style>
        .back-tester {
            background-color: #d2d2d2;
        }
    </style>
    {{--    @vite(['/resources/js/app.js']) --}}




    <!-- Include Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css" rel="stylesheet" />
    <!-- Include jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Include Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/js/select2.min.js"></script>





</head>

<body class="back-tester">
<main>
    @if (session()->has('success'))
        <div class="alert alert-success mt-5 text-center">
            {{ session()->get('success') }}
            {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
        </div>
    @endif
    @if (session()->has('warning'))
        <div class="alert alert-warning  mt-5 text-center">
            {{ session()->get('warning') }}
            {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
        </div>
    @endif
    @if (session()->has('danger'))
        <div class="alert alert-danger  mt-5 text-center">
            {{ session()->get('danger') }}
            {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
        </div>
    @endif



    {{ $slot }}
</main>

</body>
</html>

resources/views/layouts/footer.blade.php
<!-- Begin Page Footer-->
<footer class="main-footer">
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-start justify-content-lg-start justify-content-md-start justify-content-center">
            <p class="text-gradient-02">
                طراحی شده | دپارتمان انفورماتیک راهه‌کار
            </p>
        </div>
        {{-- <div
            class="col-xl-6 col-lg-6 col-md-6 col-sm-12 d-flex align-items-center justify-content-xl-end justify-content-lg-end justify-content-md-end justify-content-center">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="documentation.html">مستندات</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="changelog.html">آپدیت ها</a>
                </li>
            </ul>
        </div> --}}
    </div>
</footer>
<!-- End Page Footer -->
<a href="#" class="go-top"><i class="la la-arrow-up"></i></a>
<!-- Offcanvas Sidebar -->
</div>
<!-- End Content -->
</div>
<!-- End Page Content -->
</div>
<!-- Begin Vendor Js -->
<script src="{{ url('/') }}/assets/vendors/js/base/jquery.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/base/core.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/base/jquery.validate.min.js"></script>
<!-- End Vendor Js -->
<!-- Begin Page Vendor Js -->
<script src="{{ url('/') }}/assets/vendors/js/nicescroll/nicescroll.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/chart/chart.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/progress/circle-progress.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/calendar/moment.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/calendar/fullcalendar.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/calendar/locale/fa.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/owl-carousel/owl.carousel.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/noty/noty.min.js"></script>
<script src="{{ url('/') }}/assets/vendors/js/app/app.js?v=1.1"></script>
<script src="{{ url('/') }}/assets/vendors/js/bootstrap-wizard/bootstrap.wizard.min.js"></script>
<!-- End Page Vendor Js -->
<!-- Begin Page Snippets -->
<script src="{{ url('/') }}/assets/js/dashboard/db-default.js"></script>
<script src="{{ url('/') }}/assets/js/components/wizard/form-wizard.min.js"></script>
<!-- End Page Snippets -->
</body>

</html>

resources/views/logs/index.blade.php
@php use Illuminate\Support\Facades\Auth; @endphp


    <!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"
            defer>
    </script>

    <script src="https://cdn.tailwindcss.com"></script>


    {{-- <script
        type="text/javascript"
        src={{ asset('/assets/js/admin.js') }}
        defer
         ></script> --}}
    <meta name="_token" content="{{ csrf_token() }}">
    {{--    <script src="{{ asset('js/custom.js') }}" defer></script>--}}

    {{--    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>--}}

    <style>
        .back-tester {
            background-color: #d2d2d2;
        }
    </style>
    {{--    @vite(['/resources/js/app.js']) --}}


    <!-- Include Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css" rel="stylesheet"/>

    <!-- Include jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" defer></script>

    <!-- Include Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/js/select2.min.js" defer></script>


</head>

<body class="back-tester">
<main>
    <div>
        @if (session()->has('success'))
            <div class="alert alert-success mt-5 text-center">
                {{ session()->get('success') }}
                {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
            </div>
        @endif
        @if (session()->has('warning'))
            <div class="alert alert-warning  mt-5 text-center">
                {{ session()->get('warning') }}
                {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
            </div>
        @endif
        @if (session()->has('danger'))
            <div class="alert alert-danger  mt-5 text-center">
                {{ session()->get('danger') }}
                {{--            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">X</button> --}}
            </div>
        @endif
    </div>


    <h1 class=" mt-20 text-center text-3xl font-bold underline">
        Log
    </h1>
    <form
        class="flex flex-row justify-between w-25 mx-auto mt-20 items-center"
        action="/logs" method="get">

        <select id="searchableSelect" class="form-control">
            <option>Text</option>
            @foreach ($options as $option)
                <option value="{{ $option->id }}">{{ $option->name }}</option>
            @endforeach
        </select>

        <label>Type:
            <select name="event">
                <option value="all">All</option>
                @foreach($events as $event)
                    <option value="{{$event}}">{{ucfirst($event)}}</option>
                @endforeach
            </select>
        </label>
        <label>Type:
            <select name="log_name">
                <option value="all">All</option>
                @foreach($logNames as $logName)
                    <option value="{{$logName}}">{{ucfirst($logName)}}</option>
                @endforeach
            </select>
        </label>

        <button type="submit" class="bg-green-300 py-1 px-2 rounded">Search</button>
        <a href="/logs"
           class="text-center bg-blue-300 px-2 py-1 rounded"
        >Clear All</a>
    </form>



    <div class="text-center mt-20">
        <div class="px-5 mx-5">

            <table
                class="table text-center align-middle">
                <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Name</th>
                    <th scope="col">user</th>
                    <th scope="col">user id</th>
                    <th scope="col">subject</th>
                    <th scope="col">subject id</th>
                    <th scope="col">event</th>
                    <th scope="col" class=''>Data & Time</th>
                    <th scope="col" class="w-50">Data</th>
                </tr>
                </thead>
                <tbody>

                @foreach($activities as $activity)
                    <tr class="my-5">
                        <th scope="row">{{$activity->id}}</th>
                        <th scope="row">{{$activity->log_name}}</th>

                        <td class="">
                            {{$activity->causer ? $activity->causer->first_name.' '.$activity->causer->last_name :  'null'}}
                        </td>
                        <td class="">
                            {{$activity->causer->id ?? 'null'}}
                        </td>
                        <td class="">{{$activity->subject ? $activity->subject->first_name.' '.$activity->subject->last_name : "null"}}</td>
                        <td class="">{{$activity->subject->id ?? "null"}}</td>

                        <td>{{$activity->event}}</td>
                        <td>
                            {{$activity->created_at}}
                            {{--todo persion date--}}
                        </td>
                        <td class="w-50">
                            {{$activity->properties}}
                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
            <div class="">
                {{$activities->links()}}
            </div>
        </div>
    </div>


</main>

</body>
</html>

resources/views/logs/show.blade.php
<x-admin-layout>

    <h1 class="text-lg font-bold mt-40 mb-2 text-center px-4 py-2 rounded bg-blue-400 w-50 mx-auto">Log Data</h1>
    <div class="text-center mx-auto  block w-50  border border-2 border-fuchsia-400 rounded py-2 bg-white">

        <p class="mt-1">Log ID : {{$activity->id}}</p>
        <p class="mt-1">Log Category : {{$activity->log_name}}</p>
        <p class="mt-1 "> Event : <span class="font-bold">{{ucfirst($activity->event)}}</span></p>

        <p class="mt-1"> Caused
            By
            : {{$activity->causer ? $activity->causer->first_name.' '.$activity->causer->last_name. " (id :   ".$activity->causer->id.")" : "Unknown"}}
        {{--                : {{$activity->causer ? $activity->causer->first_name.' '.$activity->causer->last_name :  'null'}}</p>--}}


        <p class="mt-1">Performed on
            : {{$activity->subject ? class_basename($activity->subject).' Model with ID '. $activity->subject->id  : "Unknown"}}</p>
        {{--        <p class="mt-1">Subject ID : {{$activity->subject->id ?? "null"}}</p>--}}

        <p class="mt-1">Date and Time : {{$activity->created_at}}</p>
    </div>
    @if($activity->event == 'created')
        <div>
            <div class="border border-2 rounded pt-3 pb-5 px-10 w-50 mx-auto mt-20 bg-white">
                <p class="text-center mb-10 bg-green-400 px-2 py-1 rounded">Created Data</p>
                @foreach($activity->properties['attributes'] as $key => $value)
                    @if($key != 'password')
                        <p class="text-center mt-1"> {{$key}} => {{$value}}</p>
                    @endif

                @endforeach
            </div>
        </div>
    @elseif($activity->event == 'updated')
        <div class="flex flex-row justify-around mt-20 w-50 mx-auto ">

            <div class="border border-2 rounded pt-3 pb-5 px-10 bg-white">
                <p class="text-center mb-10 bg-red-400 px-2 py-1 rounded ">Old Data</p>
                @foreach($activity->properties['old'] as $key => $value)
                    <p> {{$key}} => {{$value}}</p>
                @endforeach
            </div>
            <div class="border border-2 rounded pt-3 pb-5 px-10 bg-white">
                <p class="text-center mb-10 bg-green-400 px-2 py-1 rounded">Updated Data</p>
                @foreach($activity->properties['attributes'] as $key => $value)
                    <p> {{$key}} => {{$value}}</p>
                @endforeach
            </div>
        </div>
    @elseif($activity->event == 'deleted')
        <div class="border border-2 rounded pt-3 pb-5 px-10 w-50 mx-auto mt-20 bg-white">
            <p class="text-center mb-10 bg-red-400 px-2 py-1 rounded">Old Data</p>
            @foreach($activity->properties['old'] as $key => $value)
                @if($key != 'password')
                    <p class="text-center mt-1"> {{$key}} => {{$value}}</p>
                @endif
            @endforeach
        </div>
    @else

        @if($activity->properties != [] && !empty($activity->properties))
            <div>

                <div class="border border-2 rounded pt-3 pb-5 px-10 w-50 mx-auto mt-20 bg-white">
                    <p class="text-center mb-10 bg-green-400 px-2 py-1 rounded"> Data</p>
                    @foreach($activity->properties as $key => $value)
                        @if($key != 'password')
                            <p class="text-center mt-1"> {{ucfirst($key)}} => {{$value}}</p>
                        @endif

                    @endforeach
                </div>
            </div>
        @endif
    @endif


    <div class="text-center mx-auto mt-20 "><a class=" bg-orange-500 rounded px-4 py-2 "
                                               href="/logs?key=rL05Q1vuw26I3988gZNyz2Q5v7JBNlcAPa8Ln0Tgu7SAIY2fEq"
        >Logs index</a></div>
</x-admin-layout>